name: Next.js App CI
on:
  push:
    branches: ['*']
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  all-cli-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Set environment variables
        run: mv apps/nextjs-app/.env.example apps/nextjs-app/.env
      - name: Setup pnpm
        run: corepack enable
      - name: Install dependencies (Root)
        run: pnpm install --frozen-lockfile
      - name: Build application
        run: pnpm --filter fe-agri-nextjs-app run build
      - name: Run tests
        run: pnpm --filter fe-agri-nextjs-app run test
      - name: Run linter
        run: pnpm --filter fe-agri-nextjs-app run lint
      - name: Check types
        run: pnpm --filter fe-agri-nextjs-app run check-types
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Set environment variables
        run: mv apps/nextjs-app/.env.example-e2e apps/nextjs-app/.env
      - name: Setup pnpm
        run: corepack enable
      - name: Install dependencies (Root)
        run: pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: pnpm --filter fe-agri-nextjs-app exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm --filter fe-agri-nextjs-app run test-e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            apps/nextjs-app/playwright-report/
            apps/nextjs-app/test-results/
            apps/nextjs-app/mocked-db.json
          retention-days: 30
